# 2017年统计局行政区划代码根节点
root: http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/

# rabbit mq
rabbitMQ:
  host: localhost
  port: 5672
  username: guopanbo
  password: guopanbo
  vhost: /

# 队列名称
areaQueueName: AREA_QUEUE
errorLogQueueName: ERROR_LOG_QUEUE

# 服务器不可用时重试间隔时间 （毫秒）
tryAgainIntervalTime: 30000
# 服务器不可用时重试次数
tryAgainNum: 3

# 单次处理错误的个数上限（个）
errorHandleTotalOfOnce: 100
# 处理错误闲时等待时间（毫秒）
errorHandleHandleWaitTimeForIdle: 30000